# books.py
BOOKS = [
    {"id": 1, "name": "Чунин ҷаҳони гуногун", "price": 10, "file": "books/book1.pdf"},
    {"id": 2, "name": "Дилхоҳ шахс метавонад бой шавад", "price": 10, "file": "books/book2.pdf"},
    {"id": 3, "name": "Чӣ тавр тарафи қавии худро ёбем — Саймурод Давлатов", "price": 10, "file": "books/book3.pdf"},
    {"id": 4, "name": "Андешаро дигар намо то зиндагият дигар шавад — Брайан", "price": 10, "file": "books/book4.pdf"},
    {"id": 5, "name": "Чӣ тавр дилхоҳ чизро ба дилхоҳ кас фурӯхт — Ҷо Ҷиранд", "price": 10, "file": "books/book5.pdf"},
    {"id": 6, "name": "Психологияи дурӯғ — Пол", "price": 10, "file": "books/book6.pdf"},
    {"id": 7, "name": "Сир (Тайна)", "price": 10, "file": "books/book7.pdf"},
    {"id": 8, "name": "Бойтарин одам дар Бобил", "price": 10, "file": "books/book8.pdf"},
    {"id": 9, "name": "Кӯдаки нобиғаи ман — Саймурод Давлатов", "price": 10, "file": "books/book9.pdf"},
    {"id": 10, "name": "Зан дар бораи мардон чиро намедонад", "price": 10, "file": "books/book10.pdf"},
    {"id": 11, "name": "Сармоягузории интеллектуалӣ — Бенҷамин", "price": 10, "file": "books/book11.pdf"},
    {"id": 12, "name": "Роҳҳои халосӣ аз қарз — Саймурод Давлатов", "price": 10, "file": "books/book12.pdf"},
    {"id": 13, "name": "48 қонуни қудрат — Роберт Грин", "price": 10, "file": "books/book13.pdf"},
    {"id": 14, "name": "Ман ва пул — Саймурод Давлатов", "price": 10, "file": "books/book14.pdf"},
    {"id": 15, "name": "Тарзи фикрони одамони сарватманд ва камбизоат — Саймурод Давлатов", "price": 10, "file": "books/book15.pdf"},
    {"id": 16, "name": "Фурӯшандаи пойафзол — Фил Найт", "price": 10, "file": "books/book16.pdf"},
    {"id": 17, "name": "Одатҳои атомӣ — Ҷеймс Клир", "price": 10, "file": "books/book17.pdf"},
    {"id": 18, "name": "Чунин ҷаҳони гуногун — Фэя Моран", "price": 10, "file": "books/book18.pdf"},
    {"id": 19, "name": "Таассурот ҳама чизро метавонад — Ҷон", "price": 10, "file": "books/book19.pdf"},
    {"id": 20, "name": "Аз минтақаи бароҳати худ берун шав — Брайан Трейси", "price": 10, "file": "books/book20.pdf"},
    {"id": 21, "name": "Фикр кун ва бой шав", "price": 10, "file": "books/book21.pdf"},
    {"id": 22, "name": "Қонунҳои ғолибон", "price": 10, "file": "books/book22.pdf"},
    {"id": 23, "name": "Падари фақир ва сарватманд — Роберт Киосаки", "price": 10, "file": "books/book23.pdf"},
]
